spring.application.name=OrderManagementSystem
server.port=8083

spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=1234
//spring.security.user.name=admin
//spring.security.user.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Konsolu ayarlar?
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 ile testler için konfigürasyon
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Security ayarlar?
spring.security.user.name=admin
spring.security.user.password=1234

# MySQL veritaban? konfigürasyonu (Testler için ikinci veri kayna??)
spring.datasource.secondary.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.secondary.username=your_username
spring.datasource.secondary.password=your_password
spring.jpa.secondary.database-platform=org.hibernate.dialect.MySQL5Dialect